### PR TITLE
CLI implementation

### PR DESCRIPTION
**Pull request by RaoniSilvestre**
# CLI Implementation

## What has been done

Basic CLI with current funcionality of all four previous binaries.

## Observations

Need to update scripts to work with clap or create another way to make integration testing

## Test yourself

Try something like

```bash
cargo run -- broker
```

```bash
cargo run -- consumer --help
```

etc...

### CODE REVIEW

**Comment by wyattgill9** [comment]
do you want me to confirm the PR? or do you want to continue working on it?

btw: remove the Cargo.lock file

**Comment by RaoniSilvestre** [comment]
Im gonna try to implement the script testing within rust, so doesnt have the need to approve rn

I will remove the cargo lock when i get back to work on it

**Comment by wyattgill9** [comment]
blocked merge, 
Resolve conflicts then push again. These conflicts are too complex to resolve in the web editor. Actions workflows will not trigger on activity from this pull request while it has merge conflicts.

scripts/offset_tracking_demo.sh
scripts/partitioned_demo.sh
scripts/retention_demo.sh
scripts/storage_demo.sh

**Comment by RaoniSilvestre** [comment]
Done!

**Comment by RaoniSilvestre** [comment]
Btw, the basics its done, so its approvable rn.

**Pull request merged**
